### PR TITLE
Make pictures responsive

### PR DESCRIPTION
**Pull request by ghost**
Used materialize grid and responsive-img to make photos responsive.

### CODE REVIEW

**Comment by DallasEpperson** [comment]
I'm sorry I didn't notice this before. If I don't give you a response on this pull request by 5/7 at 11:00p, shoot me a message.

**Comment by DallasEpperson** [comment]
Was there a CSS change as well, or did you intend to only check in the html page?  
  
I ask because I pulled this down, and the images themselves are not responsive. When resizing the window to arbitrary widths, the images' containers are responsive, moving to fill the space available. But the images remain at the same size. This causes the content of the images to be cut off. In other words, you'll only see the upper left section of a given image. (see below)

image
  
You should be able to fix this pretty easily by adding just a bit of css:  
```
.masonry-layout-content img {
  width: 100%
  height: 100%
}

**Comment by ghost** [comment]
Probably cache issue. Looks different for me:
image

**Comment by ghost** [comment]
Yes, there is only html change. I wanted to keep it as simple as possible because I am not yet familiar with how you guys do things, your conventions, etc. I used existing materialize css classes ([grid](https://materializecss.com/grid.html) and [responsive-img](https://materializecss.com/media-css.html)) to get this done. It's a "quick fix". 
Edit: that "upper left section of a given image" is exactly what I was trying to fix.

**Comment by DallasEpperson** [comment]
Haha yeah I see what my problem is now. I pulled from your repo, but the master branch instead of your responsivness branch. Yup, looks good to me. Merging!

**Pull request merged**
